// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest(arg1) {
  return window['go']['app']['App']['CancelRequest'](arg1);
}

export function ClearTokenCache() {
  return window['go']['app']['App']['ClearTokenCache']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetTokenStatus(arg1, arg2) {
  return window['go']['app']['App']['GetTokenStatus'](arg1, arg2);
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function OpenConfigDirectory() {
  return window['go']['app']['App']['OpenConfigDirectory']();
}

export function OpenConfigFile() {
  return window['go']['app']['App']['OpenConfigFile']();
}

export function OpenLogDirectory() {
  return window['go']['app']['App']['OpenLogDirectory']();
}

export function ReloadConfig() {
  return window['go']['app']['App']['ReloadConfig']();
}

export function SendRequest(arg1) {
  return window['go']['app']['App']['SendRequest'](arg1);
}

export function ValidateConfig() {
  return window['go']['app']['App']['ValidateConfig']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}
