// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';
import {oauth} from '../models';
import {context} from '../models';

export function CancelRequest(arg1:string):Promise<void>;

export function ClearTokenCache():Promise<void>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetTokenStatus(arg1:string,arg2:config.OAuthProfile):Promise<oauth.TokenStatus>;

export function LoadConfig():Promise<config.ConfigView>;

export function ReloadConfig():Promise<config.ConfigView>;

export function SendRequest(arg1:context.Context,arg2:config.OAuthProfile):Promise<string>;

export function ValidateConfig():Promise<config.ValidationResult>;
