// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';
import {oauth} from '../models';
import {model} from '../models';

export function CancelRequest(arg1:string):Promise<void>;

export function ClearTokenCache():Promise<void>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetTokenStatus(arg1:string,arg2:config.OAuthProfile):Promise<oauth.TokenStatus>;

export function LoadConfig():Promise<config.ConfigView>;

export function OpenConfigDirectory():Promise<void>;

export function OpenConfigFile():Promise<config.ConfigView>;

export function OpenLogDirectory():Promise<void>;

export function ReloadConfig():Promise<config.ConfigView>;

export function SendRequest(arg1:model.RequestInput):Promise<model.ResponseOutput>;

export function ValidateConfig():Promise<config.ValidationResult>;

export function ClearLogs():Promise<void>;

export function GetLogs():Promise<Array<{time:string;level:string;message:string}>>;
